[project]
name = "citable_image"
version = "0.0.2"
description = "A Python library for working images canonically citable by Cite2Urn."
readme = "README.md"
requires-python = ">=3.14"
dependencies = []