[project]
name = "citable_image"
version = "0.1.0"
description = "A Python library for working with images canonically citable by Cite2Urn."
readme = "README.md"
requires-python = ">=3.14"
dependencies = []